{{ config(materialized="table") }}


SELECT
    GEOLOCATION_ZIP_CODE_PREFIX
  , GEOLOCATION_LAT
  , GEOLOCATION_LNG
  , UPPER(TRIM(GEOLOCATION_CITY)) as GEOLOCATION_CITY
  , UPPER(TRIM(GEOLOCATION_STATE)) AS GEOLOCATION_STATE
FROM {{ source('python_ecommerce_raw_martin', 'geolocation') }}
WHERE GEOLOCATION_ZIP_CODE_PREFIX IS NOT NULL